default = 'English'
English:dict = {}
Chinese:dict = {
    "Cannot Remove The Folder, Permission denied.":"无法删除，权限不足",
    "Remove Successful!":"删除成功！",
    "Input error!":"输入错误！",
    "Alpha Edition":"阿尔法版本",
    "Detecting new version":"正在检测新版本",
    "Connect to server failed, press any button to return": "连接服务器失败，任意键返回",
    "New Version":"新版本",
    "ChangeLog":"更新日志",
    "Fix Some Bugs":"修复了一些BUG",
    "Please note that the builds in the communication group and release are always the latest development environment version. This feature is only used to detect recent stable builds":"注意，交流群与release中的构建始终为最新开发环境版本，本功能仅用于检测近期较为稳定的构建",
    "No updates found for your device, please go to https://github.com/ColdWindScholar/TIK update it yourself":"未发现适用于您设备的更新，请前往https://github.com/ColdWindScholar/TIK下载源代码自行更新",
    "Update it?[1/0]":"是否更新?[1/0]",
    "Downloading...":"正在下载新版本...",
    "Download error, please try again later":"下载错误，请稍后重试",
    "Starting update, please do not close the tool...":"开始更新，请不要关闭工具...",
    "The update file is damaged and cannot be updated":"更新文件损坏， 无法更新",
    "Update completed, any button to start a new program...":"更新完毕, 任意按钮启动新程序...",
    "You are using the latest version! Any button returns！":"你正在使用最新版本！任意按钮返回！",
    "Adjust the brotli compression level (integers 1-9):":"调整brotli压缩等级(整数1-9，级别越高，压缩率越大，耗时越长):",
    "Package Ext image size: [1]Auto [2]Origin:":"打包Ext镜像大小[1]动态最小 [2]原大小:",
    "Packing Method:":"打包方案：",
    "Pack to Sparse:":'Img是否打包为sparse镜像(压缩体积):',
    "Packaging Image Format [1]Origin [2]Selectable:":"打包镜像系统[1]同解包格式 [2]可选择:",
    "EROFS Support old Kernel[1/0]":"EROFS打包是否支持旧内核[1/0]",
    "Packing Settings":"打包设置",
    "Brotli Level":"Brotli 压缩等级",
    "EXT4 Settings":"EXT4设置",
    "Size Handle":"大小处理",
    "Packing Method":"打包方式",
    "EROFS Settings":"EROFS设置",
    "Packing Format":"压缩方式",
    "IMG Settings":"IMG设置",
    "UTC Timestamp":"UTC时间戳",
    "Pack to sparse":"创建sparse",
    "File System":"文件系统",
    "Support old Kernel":"支持旧内核",
    "Previous Menu":"返回上一级菜单",
    "Please enter the number:":"请输入编号:",
    "Optional erofs compression method[1]Yes [2]No:":"选择erofs压缩方式[1]是 [2]否:",
    "Choose erofs compression method：lz4/lz4hc/lzma/and Level[1-9] such as lz4hc,8:":"选择erofs压缩方式：lz4/lz4hc/lzma/和压缩等级[1-9](数字越大耗时更长体积更小) 例如 lz4hc,8:",
    "Set packaging UTC timestamp [1] automatic [2] customization:":"设置打包UTC时间戳[1]自动 [2]自定义:",
    "Enter:":"请输入:",
    "Set the maximum reserved size for metadata (default to 65536, at least 512):":"设置metadata最大保留size(默认为65536，至少512):",
    "Partition packaging sector/block size:":"分区打包扇区/块大小:",
    "Current dynamic partition physical partition name (default super):":"当前动态分区物理分区名(默认super):",
    "Do you want to force the creation of Super images?[1/0]":"是否强制创建Super镜像？[1/0]",
    "Mark partitions that require a Slot suffix?[1/0]":"是否标记需要Slot后缀的分区？[1/0]",
    "Dynamic partition settings":"动态分区设置",
    "Super group name":"Super簇名",
    "Metadata settings":"Metadata设置",
    "Maximum reserved size":"最大保留大小",
    "Partition settings":"分区设置",
    "Default sector/block size for partition settings":"默认扇区/块大小",
    "Super settings":"Super设置",
    "Specify block size":"指定block大小",
    "Change physical partition name":"更改物理分区名",
    "Force complete generation Img":"强制生成完整Img",
    "Mark partition slot suffix":"标记分区槽后缀"
}