default = 'English'
English:dict = {}
Russian:dict = {
    "Cannot Remove The Folder, Permission denied.": "Невозможно удалить папку, недостаточно прав.",
    "Remove Successful!": "Удаление успешно!",
    "Input error!": "Ошибка ввода!",
    "Alpha Edition": "Альфа-версия",
    "Detecting new version": "Проверка новой версии",
    "Connect to server failed, press any button to return": "Не удалось подключиться к серверу, нажмите любую кнопку для возврата",
    "New Version": "Новая версия",
    "ChangeLog": "Журнал изменений",
    "Fix Some Bugs": "Исправлены некоторые ошибки",
    "Please note that the builds in the communication group and release are always the latest development environment version. This feature is only used to detect recent stable builds": "Обратите внимание, что сборки в группе связи и в разделе релиз всегда являются последними версиями в среде разработки. Эта функция предназначена только для обнаружения последних стабильных сборок.",
    "No updates found for your device, please go to https://github.com/ColdWindScholar/TIK update it yourself": "Обновлений для вашего устройства не найдено, пожалуйста, перейдите на https://github.com/ColdWindScholar/TIK для самостоятельного обновления.",
    "Update it?[1/0]": "Обновить?[1/0]",
    "Downloading...": "Загрузка новой версии...",
    "Download error, please try again later": "Ошибка загрузки, попробуйте позже",
    "Starting update, please do not close the tool...": "Начинается обновление, пожалуйста, не закрывайте инструмент...",
    "The update file is damaged and cannot be updated": "Файл обновления поврежден, обновление невозможно",
    "Update completed, any button to start a new program...": "Обновление завершено, нажмите любую кнопку для запуска новой программы...",
    "You are using the latest version! Any button returns！": "Вы используете последнюю версию! Нажмите любую кнопку для возврата!",
    "Adjust the brotli compression level (integers 1-9):": "Настройка уровня сжатия Brotli (целые числа от 1 до 9, чем выше уровень, тем выше степень сжатия, но больше времени затрачивается):",
    "Package Ext image size: [1]Auto [2]Origin:": "Размер образа Ext: [1] Авто [2] Оригинал:",
    "Packing Method:": "Способ упаковки:",
    "Pack to Sparse:": "Упаковать в Sparse:",
    "Packaging Image Format [1]Origin [2]Selectable:": "Формат упаковки образа [1] Оригинальный [2] Выбираемый:",
    "EROFS Support old Kernel[1/0]": "EROFS: поддержка старых ядер [1/0]",
    "Packing Settings": "Настройки упаковки",
    "Brotli Level": "Уровень сжатия Brotli",
    "EXT4 Settings": "Настройки EXT4",
    "Size Handle": "Обработка размера",
    "Packing Method": "Способ упаковки",
    "EROFS Settings": "Настройки EROFS",
    "Packing Format": "Формат упаковки",
    "IMG Settings": "Настройки IMG",
    "UTC Timestamp": "UTC временная метка",
    "Pack to sparse": "Создать sparse",
    "File System": "Файловая система",
    "Support old Kernel": "Поддержка старого ядра",
    "Previous Menu": "Предыдущее меню",
    "Please enter the number:": "Введите номер:",
    "Optional erofs compression method[1]Yes [2]No:": "Выбрать метод сжатия EROFS: [1] Да [2] Нет:",
    "Choose erofs compression method：lz4/lz4hc/lzma/and Level[1-9] such as lz4hc,8:": "Выберите метод сжатия EROFS: lz4/lz4hc/lzma и уровень [1-9] (чем выше число, тем больше времени, но меньше размер), например, lz4hc,8:",
    "Set packaging UTC timestamp [1] automatic [2] customization:": "Установить UTC временную метку упаковки: [1] Автоматически [2] Ручной ввод:",
    "Enter:": "Введите:",
    "Set the maximum reserved size for metadata (default to 65536, at least 512):": "Установите максимальный резервированный размер для метаданных (по умолчанию 65536, минимум 512):",
    "Partition packaging sector/block size:": "Размер сектора/блока при упаковке раздела:",
    "Current dynamic partition physical partition name (default super):": "Имя физического раздела для динамического раздела (по умолчанию 'super'):",
    "Do you want to force the creation of Super images?[1/0]": "Принудительно создать Super-образ? [1/0]",
    "Mark partitions that require a Slot suffix?[1/0]": "Отметить разделы, требующие суффикса Slot? [1/0]",
    "Dynamic partition settings": "Настройки динамического раздела",
    "Super group name": "Имя группы Super",
    "Metadata settings": "Настройки метаданных",
    "Maximum reserved size": "Максимальный резервированный размер",
    "Partition settings": "Настройки раздела",
    "Default sector/block size for partition settings": "Размер сектора/блока по умолчанию",
    "Super settings": "Настройки Super",
    "Specify block size": "Задать размер блока",
    "Change physical partition name": "Изменить имя физического раздела",
    "Force complete generation Img": "Принудительное создание полного образа",
    "Mark partition slot suffix": "Отметить суффикс раздела Slot",
    "Tool settings": "Настройки инструмента",
    "Banner": "Баннер",
    "Online Mode": "Онлайн режим",
    "Contexts Patcher": "Патчер Contexts",
    "Language": "Язык",
    "Check Update": "Проверить обновление",
    "Select Your Language:": "Выберите ваш язык:",
    "Sickle and axe head": "Серп и топор",
    "YuanSheng": "Юаньшэн",
    "Open source Android full version ROM processing tool": "Инструмент для обработки полных версий Android ROM с открытым исходным кодом",
    "Author:": "Автор:",
    "Open Source Link:": "Ссылка на исходный код:",
    "Version:": "Версия:",
    "Open Source License:": "Лицензия с открытым исходным кодом:",
    "Thanks to:": "Благодарности:",
    "[Packaging] Related Settings": "[Настройки упаковки]",
    "[Dynamic Partition] Related Settings": "[Настройки динамического раздела]",
    "About": "О программе",
    "Home": "Главная",
    "Parse Error": "Ошибка разбора",
    "Please drag the file below or enter the path": "Перетащите файл ниже или введите путь",
    "Options": "Опции",
    "Please Enter:": "Введите:",
    "Please Enter A Value:": "Введите значение:",
    "Unsupported Widget:": "Неподдерживаемый виджет:",
    "Open source is a journey without any questions": "Открытый исходный код — это путь без вопросов",
    "Project List": "Список проектов",
    "Remove Project": "Удалить проект",
    "New Project": "Новый проект",
    "Exit": "Выход",
    "Download ROM": "Скачать ROM",
    "Enter download link:": "Введите ссылку для скачивания:",
    "Please enter the project number you want to delete:": "Введите номер проекта, который хотите удалить:",
    "Sure Delete": "Подтвердить удаление",
    "Undelete": "Отменить удаление",
    "Please Enter Project Name:": "Введите название проекта (на латинице):",
    "Project Already exists! Automatically named as:": "Проект уже существует! Автоматически переименован в:",
    "Enter to continue": "Нажмите Enter для продолжения",
    "Thank you for using TI-KITCHEN4. Goodbye！": "Спасибо за использование TI-KITCHEN5, до свидания!",
    "Processing:": "Обработка:",
    "Project:": "Проект:",
    "Incomplete": "Неполный",
    "Project Menu": "Меню проекта",
    "Unpack Menu": "Меню распаковки",
    "Pack Menu": "Меню упаковки",
    "Plugin Menu": "Меню плагинов",
    "Pack Rom": "Упаковать ROM",
    "Other Tools": "Другие инструменты",
    "Disable avb(fstab)": "Отключить avb (fstab)",
    "Magisk Patcher": "Патчер Magisk",
    "Disable data_encryption(fstab)": "Отключить шифрование данных (fstab)",
    "Please place the image to be patched in": "Поместите образ для патча в",
    "Return": "Назад",
    "Enter the Magisk.apk path:": "Введите путь к Magisk.apk:",
    "Patched Successful": "Патч успешно применён",
    "Patched Fail": "Патч не применён",
    "Pack Directly": "Упаковать напрямую",
    "Pack Hybrid Rom": "Упаковать гибридный ROM",
    "Preparing For Packing...": "Подготовка к упаковке...",
    "Device Code:": "Код устройства:",
    "ROM List": "Список ROM",
    "Please place the ROM in": "Поместите ROM в",
    "No Files!": "Файлы отсутствуют!",
    "Enter Project Name (Can Empty)：": "Введите название проекта (может быть пустым):",
    "Successful！": "Успешно!",
    "Unzipping Rom...": "Распаковка ROM...",
    "Decomposing ROM...": "Разбор ROM...",
    "A file with the same name exists:": "Файл с таким именем уже существует:",
    "Automatically renamed to": "Автоматически переименован в",
    "Writing:": "Запись:",
    "Cannot Write": "Невозможно записать",
    "Complete:": "Упаковка завершена",
    "Plugin List": "Список плагинов",
    "Uninstall": "Удалить",
    "Install": "Установить",
    "Please Enter Path of mpk:": "Введите путь к mpk (или перетащите):",
    "Not Exist！": "Не существует!",
    "Enter the plugin serial number:": "Введите номер плагина:",
    "Invalid Number": "Неверный номер",
    "is a environment, Cannot run！": "Это плагин для окружения, запуск невозможен!",
    "The plugin does not exist": "Плагин не существует",
    "Non plugin！": "Не является плагином!",
    "Enter to return": "Нажмите Enter для возврата",
    "Install Mpk": "Установить MPK",
    "Name：": "Название:",
    "Install?": "Установить?",
    "Introduce:": "Описание:",
    "Call off": "Отмена",
    "Installation failed: unsupported system": "Установка не удалась: неподдерживаемая система",
    "Installation failed: dependency not met": "Установка не удалась: не выполнены зависимости",
    "Installing...": "Установка...",
    "Please select a plugin！": "Пожалуйста, выберите плагин!",
    "The following plugins will be uninstalled simultaneously": "Следующие плагины будут удалены одновременно",
    "Uninstall?": "Удалить?",
    "Uninstalling:": "Удаление:",
    "Fail！": "Ошибка!",
    "File": "Файл",
    "Please place the file in": "Поместите файл в",
    "Unpack All": "Распаковать всё",
    "Split DAT": "Разделить DAT",
    "Split WIN": "Разделить WIN",
    "Loop Unpacking": "Циклическая распаковка",
    "Whether or not unpack all files?": "Распаковать все файлы?",
    "Whether unpack": "Распаковать?",
    "Pack Super": "Упаковать Super",
    "Pack Payload": "Упаковать Payload",
    "Whether Pack": "Упаковать?",
    "Whether Pack All": "Упаковать все образы?",
    "Pack All": "Упаковать все образы",
    "Loop Pack": "Циклическая упаковка",
    "Output file format of all": "Формат выходного файла для всех",
    "Output file format": "Формат выходного файла",
    "Pack File System:": "Файловая система для упаковки:",
    "Packing": "Упаковка...",
    "Remove Fail...": "Не удалось удалить...",
    "Decompiling dtb...": "Декомпиляция dtb...",
    "Decompile completed!": "Декомпиляция завершена!",
    "Compiling": "Компиляция...",
    "Decompiling": "Декомпиляция...",
    "Failed to compile DTB": "Не удалось скомпилировать DTB",
    "Compilation completed！": "Компиляция завершена!",
    "Unpacking": "Распаковка...",
    "Done!": "Готово!",
    "Creating": "Создание...",
    "The size you set is too small, the size will be dynamically adjusted!": "Заданный размер слишком мал, он будет автоматически увеличен!",
    "Please place the partition images that need to be packaged on the ": "Поместите образы разделов, которые нужно упаковать, в ",
    "Please Enter Super Type:": "Введите тип Super:",
    "Whether Set Attrib to Readonly?": "Установить раздел как только для чтения?",
    "Whether to package as sparse image？": "Упаковать как sparse-образ?",
    "It seems that you do not have any partitions to package. \\nDo you want to move the following partitions for packaging：": "Похоже, у вас нет разделов для упаковки.\\nПереместить следующие разделы для упаковки?",
    "Whether to execute ?": "Выполнить операцию?",
    "Choose Super.img Size:": "Выберите размер Super.img:",
    "Enter super Size（Byte）:": "Введите размер super-раздела (в байтах):",
    "Pack to": "Упаковать в",
    "Added Partition:": "Добавленный раздел:",
    "Create super.img Fail！": "Не удалось создать super.img!",
    "Create super.img Successful!": "super.img успешно создан!",
    "Unsupported:": "Неподдерживаемо:",
    "Only Support": "Поддерживается только",
    "Discovered residual Payload from previous packaging, empty it?": "Обнаружены остатки Payload от предыдущей упаковки, очистить?",
    "Please place all partition images on": "Поместите все образы разделов в",
    "It seems that you do not have any partitions to package. Do you want to move the following partitions for packaging:": "Похоже, у вас нет разделов для упаковки. Переместить следующие разделы для упаковки?",
    "Current Super logical partition table：": "Текущая логическая таблица разделов Super:",
    "What is the ROM model processor? [1] Qualcomm [2] MTK\\t": "Какой процессор используется в ROM? [1] Qualcomm [2] MTK",
    "List of partitions included：": "Список включенных разделов:",
    "Please Enter Partition names need to be decompressed (separated by spaces)/all": "Введите имена разделов для распаковки (через пробел) или 'all' для всех:",
    "Merge": "Объединить",
    "Extracting": "Извлечение...",
    "unknown format！": "Неизвестный формат!",
    "Automatic unpacking start！": "Автоматическая распаковка запущена!",
    "Do you want to delete the payload": "Удалить Payload?",
    "Pack": "Упаковать",
    "Unpack": "Распаковать",
    "Created": "Создано",
    "Create": "Создать",
    "Settings": "Настройки"
}
Chinese:dict = {
    "Cannot Remove The Folder, Permission denied.":"无法删除，权限不足",
    "Remove Successful!":"删除成功！",
    "Input error!":"输入错误！",
    "Alpha Edition":"阿尔法版本",
    "Detecting new version":"正在检测新版本",
    "Connect to server failed, press any button to return": "连接服务器失败，任意键返回",
    "New Version":"新版本",
    "ChangeLog":"更新日志",
    "Fix Some Bugs":"修复了一些BUG",
    "Please note that the builds in the communication group and release are always the latest development environment version. This feature is only used to detect recent stable builds":"注意，交流群与release中的构建始终为最新开发环境版本，本功能仅用于检测近期较为稳定的构建",
    "No updates found for your device, please go to https://github.com/ColdWindScholar/TIK update it yourself":"未发现适用于您设备的更新，请前往https://github.com/ColdWindScholar/TIK下载源代码自行更新",
    "Update it?[1/0]":"是否更新?[1/0]",
    "Downloading...":"正在下载新版本...",
    "Download error, please try again later":"下载错误，请稍后重试",
    "Starting update, please do not close the tool...":"开始更新，请不要关闭工具...",
    "The update file is damaged and cannot be updated":"更新文件损坏， 无法更新",
    "Update completed, any button to start a new program...":"更新完毕, 任意按钮启动新程序...",
    "You are using the latest version! Any button returns！":"你正在使用最新版本！任意按钮返回！",
    "Adjust the brotli compression level (integers 1-9):":"调整brotli压缩等级(整数1-9，级别越高，压缩率越大，耗时越长):",
    "Package Ext image size: [1]Auto [2]Origin:":"打包Ext镜像大小[1]动态最小 [2]原大小:",
    "Packing Method:":"打包方案：",
    "Pack to Sparse:":'Img是否打包为sparse镜像(压缩体积):',
    "Packaging Image Format [1]Origin [2]Selectable:":"打包镜像系统[1]同解包格式 [2]可选择:",
    "EROFS Support old Kernel[1/0]":"EROFS打包是否支持旧内核[1/0]",
    "Packing Settings":"打包设置",
    "Brotli Level":"Brotli 压缩等级",
    "EXT4 Settings":"EXT4设置",
    "Size Handle":"大小处理",
    "Packing Method":"打包方式",
    "EROFS Settings":"EROFS设置",
    "Packing Format":"压缩方式",
    "IMG Settings":"IMG设置",
    "UTC Timestamp":"UTC时间戳",
    "Pack to sparse":"创建sparse",
    "File System":"文件系统",
    "Support old Kernel":"支持旧内核",
    "Previous Menu":"返回上一级菜单",
    "Please enter the number:":"请输入编号:",
    "Optional erofs compression method[1]Yes [2]No:":"选择erofs压缩方式[1]是 [2]否:",
    "Choose erofs compression method：lz4/lz4hc/lzma/and Level[1-9] such as lz4hc,8:":"选择erofs压缩方式：lz4/lz4hc/lzma/和压缩等级[1-9](数字越大耗时更长体积更小) 例如 lz4hc,8:",
    "Set packaging UTC timestamp [1] automatic [2] customization:":"设置打包UTC时间戳[1]自动 [2]自定义:",
    "Enter:":"请输入:",
    "Set the maximum reserved size for metadata (default to 65536, at least 512):":"设置metadata最大保留size(默认为65536，至少512):",
    "Partition packaging sector/block size:":"分区打包扇区/块大小:",
    "Current dynamic partition physical partition name (default super):":"当前动态分区物理分区名(默认super):",
    "Do you want to force the creation of Super images?[1/0]":"是否强制创建Super镜像？[1/0]",
    "Mark partitions that require a Slot suffix?[1/0]":"是否标记需要Slot后缀的分区？[1/0]",
    "Dynamic partition settings":"动态分区设置",
    "Super group name":"Super簇名",
    "Metadata settings":"Metadata设置",
    "Maximum reserved size":"最大保留大小",
    "Partition settings":"分区设置",
    "Default sector/block size for partition settings":"默认扇区/块大小",
    "Super settings":"Super设置",
    "Specify block size":"指定block大小",
    "Change physical partition name":"更改物理分区名",
    "Force complete generation Img":"强制生成完整Img",
    "Mark partition slot suffix":"标记分区槽后缀",
    "Tool settings":"工具设置",
    "Banner":"自定义首页banner",
    "Online Mode":"联网模式",
    "Contexts Patcher":"Contexts修补",
    "Language":"语言",
    "Check Update":"检查更新",
    "Select Your Language:":"选择您的语言：",
    "Sickle and axe head":"镰刀斧头",
    "YuanSheng":"原神",
    "Open source Android full version ROM processing tool":"开源的安卓全版本ROM处理工具",
    "Author:":"作者:",
    "Open Source Link:":"开源地址:",
    "Version:":"软件版本:",
    "Open Source License:":"开源协议:",
    "Thanks to:":"特别鸣谢:",
    "[Packaging] Related Settings":"[打包]相关设置",
    "[Dynamic Partition] Related Settings":"[动态分区]相关设置",
    "About":"关于工具",
    "Home":"主页",
    "Parse Error":"解析错误",
    "Please drag the file below or enter the path":'请在下方拖入文件或输入路径',
    "Options":"选项",
    "Please Enter:":"请输入:",
    "Please Enter A Value:":"请输入一个值:",
    "Unsupported Widget:":"不支持的解析:",
    "Open source is a journey without any questions":"开源，是一场无问西东的前行",
    "Project List":"项目列表",
    "Remove Project":"删除项目",
    "New Project":"新建项目",
    "Exit":"退出",
    "Download ROM":"下载ROM",
    "Enter download link:":"输入下载链接:",
    "Please enter the project number you want to delete:":"请输入你要删除的项目序号:",
    "Sure Delete":"确认删除",
    "Undelete":"取消删除",
    "Please Enter Project Name:":"请输入项目名称(非中文)：",
    "Project Already exists! Automatically named as:":"项目已存在！自动命名为：",
    "Enter to continue":"回车以继续",
    "Thank you for using TI-KITCHEN4. Goodbye！":"感谢使用TI-KITCHEN5,再见！",
    "Processing:":"正在处理:",
    "Project:":"项目：",
    "Incomplete":"不完整",
    "Project Menu":"项目菜单",
    'Unpack Menu':"解包菜单",
    'Pack Menu':"打包菜单",
    "Plugin Menu":"插件菜单",
    "Pack Rom":"封装ROM",
    "Other Tools":"定制功能",
    "Disable avb(fstab)":"去除avb",
    "Magisk Patcher":"面具修补",
    "Disable data_encryption(fstab)":"去除data加密",
    "Please place the image to be patched in":"请将要修补的镜像放入",
    "Return":"返回",
    "Enter the Magisk.apk path:":"请输入Magisk.apk路径:",
    "Patched Successful":"修补完成",
    "Patched Fail":"修补失败",
    "Pack Directly":"直接打包",
    "Pack Hybrid Rom":"卡线一体",
    "Preparing For Packing...":"正在准备打包...",
    "Device Code:":"打包卡线一体限制机型代号:",
    "ROM List":"ROM列表",
    "Please place the ROM in":"请将ROM放置于",
    "No Files!":"没有文件!",
    "Enter Project Name (Can Empty)：":"请输入项目名称(可留空)：",
    "Successful！":"成功!",
    "Unzipping Rom...":"解压刷机包中...",
    "Decomposing ROM...":"分解ROM中...",
    "A file with the same name exists:":"存在同名文件：",
    "Automatically renamed to":"已自动重命名为",
    "Writing:":"正在写入:",
    "Cannot Write":"无法写入",
    "Complete:":"打包完成",
    "Plugin List":"插件列表",
    "Uninstall":"卸载",
    "Install":"安装",
    "Please Enter Path of mpk:":"请输入插件路径或[拖入]:",
    "Not Exist！":"不存在！",
    "Enter the plugin serial number:":"输入插件序号:",
    "Invalid Number":"序号错误",
    "is a environment, Cannot run！":"为环境插件，不可运行！",
    "The plugin does not exist":"插件不存在",
    "Non plugin！":"非插件！",
    "Enter to return":"回车返回",
    "Install Mpk":"安装MPK",
    "Name：":"名称：",
    "Install?":"要安装吗?",
    "Introduce:":"介绍",
    "Call off":"取消",
    "Installation failed: unsupported system":"安装失败:不支持的系统",
    "Installation failed: dependency not met":"安装失败:不满足依赖",
    "Installing...":"正在安装...",
    "Please select a plugin！":"请选择插件！",
    "The following plugins will be uninstalled simultaneously":"将会同时卸载以下插件",
    "Uninstall?":"确定卸载吗",
    "Uninstalling:":"正在卸载:",
    "Fail！":"失败！",
    "File":"文件",
    "Please place the file in":"请将文件放于",
    "Unpack All":"分解所有文件",
    "Split DAT":"分段DAT",
    "Split WIN":"分段WIN",
    "Loop Unpacking":"循环解包",
    "Whether or not unpack all files?":" 是否解包所有文件?",
    "Whether unpack":"是否解包",
    "Pack Super":"打包 Super",
    "Pack Payload":"打包 Payload",
    "Whether Pack":"是否打包",
    "Whether Pack All":"是否打包所有镜像",
    "Pack All":"打包所有镜像",
    "Loop Pack":"循环打包",
    "Output file format of all":"输出所有的文件格式",
    "Output file format":"输出文件格式",
    "Pack File System:":"手动打包所有分区格式为：",
    "Packing":"正在打包",
    "Remove Fail...":"删除失败",
    "Decompiling dtb...":"正在反编译dtb...",
    "Decompile completed!":"反编译完成!",
    "Compiling":'正在回编译',
    "Decompiling":'正在反编译',
    "Failed to compile DTB":"回编译dtb失败",
    "Compilation completed！":"回编译完成！",
    "Unpacking":"正在解包",
    "Done!":"完成",
    "Creating":"正在生成",
    "The size you set is too small, the size will be dynamically adjusted!":"您设置的size过小,将动态调整size!",
    "Please place the partition images that need to be packaged on the ":"请将需要打包的分区镜像放置于",
    "Please Enter Super Type:":"请输入Super类型:",
    "Whether Set Attrib to Readonly?":"是否设置为只读分区？",
    "Whether to package as sparse image？":"是否打包为sparse镜像？",
    "It seems that you do not have any partitions to package. \nDo you want to move the following partitions for packaging：":"您似乎没有要打包的分区，要移动下列分区打包吗：",
    "Whether to execute ?":"确定操作吗",
    "Choose Super.img Size:":"请设置Super.img大小:",
    "Enter super Size（Byte）:":"请输入super分区大小（字节数）:",
    "Pack to":"打包到",
    "Added Partition:":"已添加分区:",
    "Create super.img Fail！":"创建super.img失败！",
    "Create super.img Successful!":"成功创建super.img!",
    "Unsupported:":"不支持：",
    "Only Support":"只支持",
    "Discovered residual Payload from previous packaging, empty it?":"发现之前打包Payload残留，清空吗",
    "Please place all partition images on":"请将所有分区镜像放置于",
    "It seems that you do not have any partitions to package. Do you want to move the following partitions for packaging:":"您似乎没有要打包的分区，要移动下列分区打包吗：",
    "Current Super logical partition table：":"当前Super逻辑分区表：",
    "What is the ROM model processor? [1] Qualcomm [2] MTK	":"ROM机型处理器为？[1]高通 [2]MTK	",
    "List of partitions included：":"所含分区列表：",
    "Please Enter Partition names need to be decompressed (separated by spaces)/all":"请输入需要解压的分区名(空格隔开)/all[全部]",
    "Merge":"合并",
    "Extracting":"正在提取",
    "unknown format！":"未知格式!",
    "Automatic unpacking start！":"自动解包开始！",
    "Do you want to delete the payload":"你要删除payload吗",
    "Pack":"打包",
    "Unpack":"解压",
    "Created":"已创建",
    "Create":"创建",
    "Settings":"设置",
}